Added inputs to model class and defined construct_param_dict function
Adrian-Mag/Pharmakinetic_project pull request #11
Opened 2022-10-19 15:09 UTC by synapsidfan

Established the input parameters for the model class and defined the function to create a dictionary of parameters.

2022-10-19 16:08 UTC, sscivier requested changes
Dictionary generation looks good. Some cleaning up needed. Add testing to make sure the class and methods are working as you expect. Unittests currently failing because they haven't been updated.

2022-10-19 16:08 UTC, sscivier commented on pkmodel/model.py
> +
Are these lines needed now?

2022-10-19 16:08 UTC, sscivier commented on pkmodel/model.py
> +        self.opt_params = [K_a, Q_p1, Q_p2, V_p1, V_p2]
Duplication between the parameters in the list and not in the list.

2022-10-19 16:08 UTC, sscivier commented on pkmodel/model.py
> +    #     return [dqc_dt, dqp1_dt]
Remove?

2022-10-20 10:28 UTC, Adrian-Mag approved these changes

2022-10-20 13:25 UTC, sscivier approved these changes
One comment re adding a little info to docstrings but otherwise good

2022-10-20 13:25 UTC, merged